In [1]:
import torch
from ProjectModule import *
import pandas as pd
import pickle

ModuleNotFoundError: No module named 'ProjectModule'

In [ ]:
input_size = 28
hidden_dim = 128
n_layers = 2
dropout = 0.9
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

water_lstm_model = LSTMModel(input_size = input_size, hidden_dim = hidden_dim,
                       n_layers = n_layers, dropout = dropout, bidirectional = True).to(DEVICE)


water_lstm_model.load_state_dict(torch.load(r'C:\Users\KDP-2\OneDrive\바탕 화면\Python\기업 프로젝트\water_best_model_0.91.pth', map_location = torch.device('cpu')))
water_lstm_model.eval()


C:\Users\KDP-2\AppData\Local\Temp\ipykernel_24528\4106913018.py:11: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  water_lstm_model.load_state_dict(torch.load(r'C:\Users\KDP-

LSTMModel(
  (model): LSTM(28, 128, num_layers=2, batch_first=True, dropout=0.9, bidirectional=True)
  (linear): Linear(in_features=256, out_features=1, bias=True)
)

In [ ]:
input_size = 28
hidden_dim = 32
n_layers = 2
dropout = 0.9
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

electric_lstm_model = LSTMModel(input_size = input_size, hidden_dim = hidden_dim,
                       n_layers = n_layers, dropout = dropout, bidirectional = True).to(DEVICE)

electric_lstm_model.load_state_dict(torch.load(r'C:\Users\KDP-2\OneDrive\바탕 화면\Python\기업 프로젝트\model_weights_73_0.8415.pth', map_location = torch.device('cpu')))
electric_lstm_model.eval()

C:\Users\KDP-2\AppData\Local\Temp\ipykernel_24528\356359432.py:10: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  electric_lstm_model.load_state_dict(torch.load(r'C:\Users\KD

LSTMModel(
  (model): LSTM(28, 32, num_layers=2, batch_first=True, dropout=0.9, bidirectional=True)
  (linear): Linear(in_features=64, out_features=1, bias=True)
)

In [ ]:
featureDF = pd.DataFrame(columns = range(28))
featureDF.loc[0] = [148,36,320,185,138,50,460,192,176,60,132,137,140,30,186,152,40,58,128,136,139,32,182,148,40,80,152, 290
]
featureDF

0   1    2    3    4   5    6    7    8   9   ...   18   19   20  21   22  \
0  148  36  320  185  138  50  460  192  176  60  ...  128  136  139  32  182   

    23  24  25   26   27  
0  148  40  80  152  290  

[1 rows x 28 columns]

In [ ]:

with open(r'C:\Users\KDP-2\OneDrive\바탕 화면\Python\기업 프로젝트\electric_min_max_scaler.pkl', 'rb') as f:
    electric_scaler = pickle.load(f)

with open(r'C:\Users\KDP-2\OneDrive\바탕 화면\Python\기업 프로젝트\water_robust_scaler.pkl', 'rb') as f:
    water_scaler = pickle.load(f)

electric_scaled_df = electric_scaler.transform(featureDF)
water_scaled_df = water_scaler.transform(featureDF)

electric_featureTS = torch.FloatTensor(electric_scaled_df)
water_featureTS = torch.FloatTensor(water_scaled_df)

electric_result = electric_lstm_model(electric_featureTS)
water_result = water_lstm_model(water_featureTS)

water_result

c:\Users\KDP-2\anaconda3\envs\Project_38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\KDP-2\anaconda3\envs\Project_38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RobustScaler was fitted with feature names
  warnings.warn(


tensor([[283.2565]], grad_fn=<AddmmBackward0>)

In [ ]:
electric_featureDF = pd.DataFrame(columns = range(28))
electric_featureDF.loc[0] = [1.72,1.59,1.23,1.44,1.89,1.65,1.26,1.36,1.68,1.63,1.20,1.38,1.70,1.58,1.22,1.42,1.69,1.51,1.24,1.39,1.74,1.62,1.28,1.43,1.78,1.60,1.25,1.25]

water_featureDF = pd.DataFrame(columns = range(28))
water_featureDF.loc[0] = [145,140,32,310,180,135,48,450,192,170,58,128,130,136,30,185,152,40,54,132,134,136,27,180,148,35,76,152
]

electric_scaled_df = electric_scaler.transform(electric_featureDF)
water_scaled_df = water_scaler.transform(water_featureDF)

electric_featureTS = torch.FloatTensor(electric_scaled_df)
water_featureTS = torch.FloatTensor(water_scaled_df)

electric_result = electric_lstm_model(electric_featureTS)
water_result = water_lstm_model(water_featureTS)

print(water_featureDF)
print(water_featureTS)
print(electric_result, water_result)

    0    1   2    3    4    5   6    7    8    9   ...  18   19   20   21  22  \
0  145  140  32  310  180  135  48  450  192  170  ...  54  132  134  136  27   

    23   24  25  26   27  
0  180  148  35  76  152  

[1 rows x 28 columns]
tensor([[-0.0180, -0.0631, -1.0360,  1.4685,  0.2973, -0.1081, -0.8919,  2.7297,
          0.4054,  0.2072, -0.8018, -0.1712, -0.1532, -0.0991, -1.0541,  0.3423,
          0.0450, -0.9640, -0.8378, -0.1351, -0.1140, -0.0991, -1.0811,  0.2973,
          0.0090, -1.0090, -0.6396,  0.0450]])
tensor([[1.3029]], grad_fn=<AddmmBackward0>) tensor([[294.9832]], grad_fn=<AddmmBackward0>)


c:\Users\KDP-2\anaconda3\envs\Project_38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\KDP-2\anaconda3\envs\Project_38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RobustScaler was fitted with feature names
  warnings.warn(


In [ ]:
electric_result * 1.1

tensor([[1.4331]], grad_fn=<MulBackward0>)

In [ ]:
from .Module.ProjectModule import *

['LSTMModel', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'nn', 'torch']


In [ ]:
WATER_MODEL_PATH = './water_best_model_0.91.pth'
ELECTRIC_MODEL_PATH = './model_weights_73_0.8415.pth'

WATER_SCALER_PATH = './water_robust_scaler.pkl'
ELECTRIC_SCALER_PATH = './electric_min_max_scaler.pkl'

water_inputs = [145,140,32,310,180,135,48,450,192,170,58,128,130,136,30,185,152,40,54,132,134,136,27,180,148,35,76,152]
electric_inputs = [1.72,1.59,1.23,1.44,1.89,1.65,1.26,1.36,1.68,1.63,1.20,1.38,1.70,1.58,1.22,1.42,1.69,1.51,1.24,1.39,1.74,1.62,1.28,1.43,1.78,1.60,1.25,1.25]

water_TS = preprocessing(water_inputs, WATER_SCALER_PATH)
electric_TS = preprocessing(electric_inputs, ELECTRIC_SCALER_PATH)

water_model = load_water_model(WATER_MODEL_PATH)
electric_model = load_electric_model(ELECTRIC_MODEL_PATH)

water_predict_value, electric_predict_value = predict_values(water_model, electric_model, water_TS, electric_TS)

NameError: name 'preprocessing' is not defined

In [ ]:
print(dir(ProjectModule))

['LSTMModel', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'nn', 'torch']
