In [2]:
from LSTMAutoEncoderModule import *
import torch
import torch.nn as nn
import numpy as np
import pickle

In [3]:
# ELEC_SCALER_PATH = './electric_min_max_scaler.pkl'
# WATER_SCALER_PATH = './water_robust_scaler.pkl'

ELEC_MODEL_PATH = './model_weights_89.pth'
WATER_MODEL_PATH = './model_weights_166.pth'

In [4]:
# water_list = [93,49,-93,-72,-36,194,-107,-50,60,111,-81,-27,37,23,-72,-51,65,77,-73,-47,93,49,-93,-20,10,0,0]
elec_list = [1.23, 1.45, 1.73, 1.62, 1.31, 1.48, 1.74, 1.71, 1.3, 1.49, 1.94, 1.68, 1.26, 1.39, 1.69, 1.61, 1.28, 1.44, 1.77, 1.68, 1.2, 1.42, 1.88, 1.67, 1.3, 1.3, 1.3, 1.3]

In [5]:
# with open(ELEC_SCALER_PATH, 'rb') as f:
#     elec_scaler = pickle.load(f)

# with open(WATER_SCALER_PATH, 'rb') as f:
#     water_scaler = pickle.load(f)

elec_df = pd.DataFrame(columns = range(28))
elec_df.loc[0] = elec_list

# water_df = pd.DataFrame(columns = range(27))
# water_df.loc[0] = water_list

# scaled_elec = elec_scaler.transform(elec_df)
# scaled_water = water_scaler.transform(water_df)

elec_ts = torch.FloatTensor([elec_df.iloc[0]])
# water_ts = torch.FloatTensor(scaled_water)

elec_ts



tensor([[1.2300, 1.4500, 1.7300, 1.6200, 1.3100, 1.4800, 1.7400, 1.7100, 1.3000,
         1.4900, 1.9400, 1.6800, 1.2600, 1.3900, 1.6900, 1.6100, 1.2800, 1.4400,
         1.7700, 1.6800, 1.2000, 1.4200, 1.8800, 1.6700, 1.3000, 1.3000, 1.3000,
         1.3000]])

In [6]:
water_ts

NameError: name 'water_ts' is not defined

In [ ]:
input_size = 27
hidden_dim = 128

water_model = VanillaModel(input_size = input_size, hidden_dim = hidden_dim)
water_model.load_state_dict(torch.load(WATER_MODEL_PATH, map_location = torch.device('cpu'), weights_only = True))
water_model.eval()

water_predict_value = water_model(water_ts)
water_predict_value

NameError: name 'VanillaModel' is not defined

In [7]:
input_size = 28
latent_dim = 16
n_layers = 2

elec_model = LSTMAutoEncoderModel(input_size = input_size, latent_dim = latent_dim, n_layers = n_layers)
elec_model.load_state_dict(torch.load(ELEC_MODEL_PATH, map_location = torch.device('cpu'), weights_only = True))
elec_model.eval()

elec_predict_value = elec_model(elec_ts)
elec_predict_value

tensor([[1.3438, 1.4833, 1.8344, 1.6146, 1.3192, 1.4232, 1.7574, 1.6419, 1.2968,
         1.4689, 1.7284, 1.6110, 1.2833, 1.3159, 1.6722, 1.6406, 1.3069, 1.4191,
         1.8244, 1.6255, 1.2451, 1.3549, 1.8452, 1.7039, 1.2644, 1.3868, 1.4106,
         1.3193]], grad_fn=<AddmmBackward0>)

In [ ]:
elec_list

[1.23,
 1.45,
 1.73,
 1.62,
 1.31,
 1.48,
 1.74,
 1.71,
 1.3,
 1.49,
 1.94,
 1.68,
 1.26,
 1.39,
 1.69,
 1.61,
 1.28,
 1.44,
 1.77,
 1.68,
 1.2,
 1.42,
 1.88,
 1.67,
 1.3,
 1.3,
 1.3,
 1.3]

In [ ]:
nn.L1Loss()(elec_ts, elec_predict_value)

tensor(0.0585, grad_fn=<MeanBackward0>)

In [ ]:
input_size = 28
hidden_dim = 64

water_model = VanillaModel(input_size = input_size, hidden_dim = hidden_dim)
water_model.load_state_dict(torch.load(WATER_MODEL_PATH, map_location = torch.device('cpu'), weights_only = True))
water_model.eval()

water_predict_value = water_model(water_ts)
water_predict_value

tensor([[-1.3244, -1.3244, -1.3244,  0.8375, -1.2344,  3.1784,  0.5044,  0.6213,
         -0.9368, -0.1010,  0.3785, -0.5680, -0.8375, -0.0541,  0.3681, -0.4689,
         -0.9097, -0.0727,  0.5099,  0.4595, -0.8462,  0.1329,  0.5670,  0.0267,
          3.2718,  2.5486,  3.1794,  3.1798]], grad_fn=<AddmmBackward0>)

In [ ]:
water_ts

tensor([[-1.3243, -1.3243, -1.3243,  0.8378, -1.2342,  3.1802,  0.5045,  0.6216,
         -0.9369, -0.0991,  0.3784, -0.5676, -0.8378, -0.0541,  0.3694, -0.4685,
         -0.9099, -0.0721,  0.5135,  0.4595, -0.8468,  0.1351,  0.5676,  0.0270,
          3.2703,  2.5495,  3.1802,  3.1802]])

In [ ]:
nn.L1Loss()(water_ts, water_predict_value)

tensor(0.0007, grad_fn=<MeanBackward0>)