In [2]:
l = [[1, 2, 3], [4, 5, 6]]
type(l)

list

In [3]:
l[0]

[1, 2, 3]

In [4]:
l[1]

[4, 5, 6]

In [5]:
for i, a in enumerate(l):
    for j, b in enumerate(a):
        print(l[i][j])

1
2
3
4
5
6


In [6]:
import numpy as np

np.__version__

'1.24.2'

In [7]:
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [8]:
l = [1, 2, 3, 4]
a = np.array(l)
a

array([1, 2, 3, 4])

In [9]:
type(a)

numpy.ndarray

In [10]:
t = (1, 2, 3, 4)
b = np.array(t)
type(b)

numpy.ndarray

In [11]:
a.data

In [12]:
a.data.obj

array([1, 2, 3, 4])

In [13]:
type(a.data.obj)

numpy.ndarray

In [14]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2.shape

(2, 3)

In [15]:
a2.ndim

2

In [16]:
a2.dtype

dtype('int32')

In [17]:
a2.itemsize

4

In [18]:
a2.size

6

In [19]:
a2.strides

(12, 4)

In [20]:
np.ndarray.__bases__

(object,)

In [21]:
np.matrix.__bases__

(numpy.ndarray,)

In [22]:
(a != 0).any

<function ndarray.any>

In [23]:
np.any

<function numpy.any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)>

In [24]:
np.ndarray.any is np.core.fromnumeric.any

False

In [25]:
np_ = set(dir(np))
nd_ = set(dir(np.ndarray))

npd_ = np_ & nd_
len(npd_)

48

In [26]:
count = 0
for i in list(npd_):
    count += 1
    print(i, end = " ")
    if count % 5 == 0:
        print()

ptp sort partition nbytes resize 
shape mean min squeeze var 
round std trace any cumprod 
all imag diagonal nonzero compress 
take __doc__ repeat sum choose 
transpose argsort put __dir__ conjugate 
max size dtype dot ndim 
cumsum swapaxes argmax reshape ravel 
real searchsorted argpartition conj clip 
prod copy argmin 

In [27]:
a = dir(np)
np.ufunc

numpy.ufunc

In [28]:
count = 0
for i in a:
    if (i == "Tester") | (i == "testing"):
        continue
    if type(np.__dict__[i]) == np.ufunc:
        print(i, end = " ")
        count += 1
        if count % 5 == 0:
            print()

abs absolute add arccos arccosh 
arcsin arcsinh arctan arctan2 arctanh 
bitwise_and bitwise_not bitwise_or bitwise_xor cbrt 
ceil conj conjugate copysign cos 
cosh deg2rad degrees divide divmod 
equal exp exp2 expm1 fabs 
float_power floor floor_divide fmax fmin 
fmod frexp gcd greater greater_equal 
heaviside hypot invert isfinite isinf 
isnan isnat lcm ldexp left_shift 
less less_equal log log10 log1p 
log2 logaddexp logaddexp2 logical_and logical_not 
logical_or logical_xor matmul maximum minimum 
mod modf multiply negative nextafter 
not_equal positive power rad2deg radians 
reciprocal remainder right_shift rint sign 
signbit sin sinh spacing sqrt 
square subtract tan tanh true_divide 
trunc 

In [29]:
a = np.arange(6, 10)
a

array([6, 7, 8, 9])

In [30]:
b = np.arange(10, 14)
b

array([10, 11, 12, 13])

In [31]:
c = a * b
c

array([ 60,  77,  96, 117])

In [32]:
a2 = np.array([1, 2, 3, 4])
a2

array([1, 2, 3, 4])

In [33]:
a2 = a2.reshape(2, 2)
a2

array([[1, 2],
       [3, 4]])

In [34]:
np.sum(a2)

10

In [35]:
np.sum(a2, axis = 0)

array([4, 6])

In [36]:
np.sum(a2, axis = 1)

array([3, 7])

In [37]:
a = np.array([4, 5])
a.shape

(2,)

In [38]:
b = np.array([3, 4, 6])
b.shape

(3,)

In [39]:
try:
    a + b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


In [40]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [41]:
b = a

In [42]:
b

array([[1, 2],
       [3, 4]])

In [43]:
b[0] = 999
a

array([[999, 999],
       [  3,   4]])

In [44]:
b

array([[999, 999],
       [  3,   4]])

In [45]:
f = np.array([4, 5, 6, 7, 8])
e = f.copy()

g = f[:]
g.base


array([4, 5, 6, 7, 8])

In [46]:
np.may_share_memory(g, f)

True

In [47]:
l = list(range(1, 10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
index = 1
l.__getitem__(index)

2

In [49]:
index = slice(1, 3)
l.__getitem__(index)

[2, 3]

In [50]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
index = 1
a.__getitem__(index)

2

In [51]:
index = slice(1, 3)
a.__getitem__(index)

array([2, 3])

In [52]:
index = 1
a.__getitem__(index)

2

In [53]:
index = [1]
a.__getitem__(index)

array([2])

In [54]:
index = a < 4
index

array([ True,  True,  True, False, False, False, False])

In [55]:
a.__getitem__(index)

array([1, 2, 3])

In [56]:
a = np.array(43)
type(a)


numpy.ndarray

In [57]:
a

array(43)

In [58]:
a.ndim

0

In [59]:
a.shape

()

In [60]:
a.dtype

dtype('int32')

In [61]:
a == 43

True

In [62]:
v = np.array([43])
type(v)

numpy.ndarray

In [63]:
v

array([43])

In [64]:
v.ndim

1

In [65]:
v.shape

(1,)

In [66]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
v.dtype

dtype('int32')

In [68]:
v1 = np.arange(10.5, 20.5, 0.5)
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [69]:
v1.dtype

dtype('float64')

In [70]:
v1.size

20

In [71]:
la = np.linspace(1, 10, 10)
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [72]:
la.dtype

dtype('float64')

In [73]:
la1 = np.linspace(1, 10, 10, endpoint = False, retstep = True)
la1

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [74]:
lo = np.logspace(0, 2, 4)
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [75]:
la2 = np.linspace(0, 2, 4)
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [76]:
for i in la2:
    print(np.power(10, i))

1.0
4.641588833612778
21.544346900318832
100.0


In [77]:
v = np.arange(3, 5)
v

array([3, 4])

In [78]:
np.hypot(v[0], v[1])

5.0

In [79]:
v_p = np.power(v, 2)

In [80]:
v_r = np.sqrt(np.sum(v_p))
v_r

5.0

In [81]:
np.linalg.norm(v)

5.0

In [82]:
e1 = np.array([1, 0, 0])
np.linalg.norm(e1)

1.0

In [83]:
e2 = np.array([0, 1, 0])
np.linalg.norm(e2)

1.0

In [84]:
e3 = np.array([0, 0, 1])
np.linalg.norm(e3)

1.0

In [85]:
v_3 = np.array([1, 2, 3])
v_3_n = np.linalg.norm(v_3)
v_3_n

3.7416573867739413

In [86]:
v_3_u = v_3 / v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [87]:
np.linalg.norm(v_3_u)

1.0

In [88]:
a = np.arange(3, 5)
b = np.arange(3, 5)
np.array_equal(a, b)

True

In [89]:
a_1 = np.linalg.norm(a)
b_1 = np.linalg.norm(b)
a_1 == b_1

True

In [90]:
c = np.arange(10, 13)
d = np.arange(0, 3)
np.sqrt(np.sum(np.square(c - d)))

17.320508075688775

In [91]:
np.linalg.norm(c - d)

17.320508075688775

In [92]:
A = np.array([[43], [44]])
type(A)

numpy.ndarray

In [93]:
A

array([[43],
       [44]])

In [94]:
A.dtype

dtype('int32')

In [95]:
A.ndim

2

In [96]:
A.shape

(2, 1)

In [97]:
c1 = np.array([[1, 2, 4], [2, 4, 8], [3, 4, 5]])
np.linalg.matrix_rank(c1)

2

In [98]:
c2 = np.array([[1, 3, 4], [1, 8, 5], [2, 3, 4]])
np.linalg.matrix_rank(c2)

3

In [99]:
np.linalg.det(c1)

0.0

In [100]:
c1[0] * 2 - c1[1]

array([0, 0, 0])

In [101]:
np.linalg.det(c2)

-17.0

In [102]:
np.linalg.matrix_rank(c2.T)

3

In [103]:
A = np.array([[2, 3], [4, 5]])
A.sum()

14

In [104]:
A.sum(axis = 0)

array([6, 8])

In [105]:
A.sum(axis = 1)

array([5, 9])

In [106]:
C = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
C.ndim

3

In [107]:
C.shape

(2, 2, 2)

In [108]:
C[0]

array([[1, 2],
       [3, 4]])

In [109]:
C[1]

array([[5, 6],
       [7, 8]])

In [110]:
C.sum(axis = 0)

array([[ 6,  8],
       [10, 12]])

In [111]:
C.sum(axis = 1)

array([[ 4,  6],
       [12, 14]])

In [112]:
C.sum(axis = 2)

array([[ 3,  7],
       [11, 15]])

In [113]:
x = np.array([1, 2])
x

array([1, 2])

In [114]:
x = np.array([[1, 4, 5], [4, 5, 6], [7, 8, 9]])
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
y = np.expand_dims(x, axis = 1)
y

array([[[1, 4, 5]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [116]:
z = np.expand_dims(x, axis = 0)
z

array([[[1, 4, 5],
        [4, 5, 6],
        [7, 8, 9]]])

In [117]:
x.flatten()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [118]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [119]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [120]:
a.shape

(3, 3)

In [121]:
np.trace(a)

14

In [122]:
a.trace()

14

In [123]:
b = np.array([[1, 0, 0], [0, 3, 0], [0, 0, 5]])
b

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [124]:
b.diagonal()

array([1, 3, 5])

In [125]:
np.diagonal(b)

array([1, 3, 5])

In [126]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [128]:
b = np.arange(1, 10).reshape(3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
np.triu(b)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [130]:
X = np.array([[1, 2, 3], [2, 3, 5], [3, 5, 6]])
X

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [131]:
np.array_equal(X, X.T)

True

In [132]:
np.array_equiv(X, X.T)

True

In [133]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
b = np.eye(3, dtype = 'int')
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [135]:
np.dot(a, b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
c = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
np.dot(a, c)

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [137]:
from scipy.stats import ortho_group

In [138]:
x = ortho_group.rvs(3)

In [139]:
x

array([[-0.04186348,  0.58122894, -0.81266252],
       [ 0.58837608,  0.67172114,  0.45011587],
       [-0.80750296,  0.45930777,  0.37010179]])

In [140]:
i3 = np.dot(x, x.T)
i3

array([[1.00000000e+00, 3.65303594e-16, 3.32793036e-16],
       [3.65303594e-16, 1.00000000e+00, 1.52792201e-16],
       [3.32793036e-16, 1.52792201e-16, 1.00000000e+00]])

In [141]:
c = np.eye(3)
np.allclose(c, i3)

True

In [142]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [143]:
a.T

array([[1, 3],
       [2, 4]])

In [144]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [145]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [146]:
v = np.array([1,2,3,4,5])
v[0]

1

In [147]:
v[-1]

5

In [148]:
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
A[0]

array([1, 2, 3, 4, 5])

In [149]:
A[-1]

array([ 6,  7,  8,  9, 10])

In [151]:
B = np.arange(9).reshape(3, 3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])