In [279]:
l = [[1, 2, 3], [4, 5, 6]]
type(l)

list

In [280]:
l[0]

[1, 2, 3]

In [281]:
l[1]

[4, 5, 6]

In [282]:
for i, a in enumerate(l):
    for j, b in enumerate(a):
        print(l[i][j])

1
2
3
4
5
6


In [283]:
import numpy as np

np.__version__

'1.24.2'

In [284]:
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [285]:
l = [1, 2, 3, 4]
a = np.array(l)
a

array([1, 2, 3, 4])

In [286]:
type(a)

numpy.ndarray

In [287]:
t = (1, 2, 3, 4)
b = np.array(t)
type(b)

numpy.ndarray

In [288]:
a.data

In [289]:
a.data.obj

array([1, 2, 3, 4])

In [290]:
type(a.data.obj)

numpy.ndarray

In [291]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2.shape

(2, 3)

In [292]:
a2.ndim

2

In [293]:
a2.dtype

dtype('int32')

In [294]:
a2.itemsize

4

In [295]:
a2.size

6

In [296]:
a2.strides

(12, 4)

In [297]:
np.ndarray.__bases__

(object,)

In [298]:
np.matrix.__bases__

(numpy.ndarray,)

In [299]:
(a != 0).any

<function ndarray.any>

In [300]:
np.any

<function numpy.any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)>

In [301]:
np.ndarray.any is np.core.fromnumeric.any

False

In [302]:
np_ = set(dir(np))
nd_ = set(dir(np.ndarray))

npd_ = np_ & nd_
len(npd_)

48

In [303]:
count = 0
for i in list(npd_):
    count += 1
    print(i, end = " ")
    if count % 5 == 0:
        print()

ptp sort partition nbytes resize 
shape mean min squeeze var 
round std trace any cumprod 
all imag diagonal nonzero compress 
take __doc__ repeat sum choose 
transpose argsort put __dir__ conjugate 
max size dtype dot ndim 
cumsum swapaxes argmax reshape ravel 
real searchsorted argpartition conj clip 
prod copy argmin 

In [304]:
a = dir(np)
np.ufunc

numpy.ufunc

In [305]:
count = 0
for i in a:
    if (i == "Tester") | (i == "testing"):
        continue
    if type(np.__dict__[i]) == np.ufunc:
        print(i, end = " ")
        count += 1
        if count % 5 == 0:
            print()

abs absolute add arccos arccosh 
arcsin arcsinh arctan arctan2 arctanh 
bitwise_and bitwise_not bitwise_or bitwise_xor cbrt 
ceil conj conjugate copysign cos 
cosh deg2rad degrees divide divmod 
equal exp exp2 expm1 fabs 
float_power floor floor_divide fmax fmin 
fmod frexp gcd greater greater_equal 
heaviside hypot invert isfinite isinf 
isnan isnat lcm ldexp left_shift 
less less_equal log log10 log1p 
log2 logaddexp logaddexp2 logical_and logical_not 
logical_or logical_xor matmul maximum minimum 
mod modf multiply negative nextafter 
not_equal positive power rad2deg radians 
reciprocal remainder right_shift rint sign 
signbit sin sinh spacing sqrt 
square subtract tan tanh true_divide 
trunc 

In [306]:
a = np.arange(6, 10)
a

array([6, 7, 8, 9])

In [307]:
b = np.arange(10, 14)
b

array([10, 11, 12, 13])

In [308]:
c = a * b
c

array([ 60,  77,  96, 117])

In [309]:
a2 = np.array([1, 2, 3, 4])
a2

array([1, 2, 3, 4])

In [310]:
a2 = a2.reshape(2, 2)
a2

array([[1, 2],
       [3, 4]])

In [311]:
np.sum(a2)

10

In [312]:
np.sum(a2, axis = 0)

array([4, 6])

In [313]:
np.sum(a2, axis = 1)

array([3, 7])

In [314]:
a = np.array([4, 5])
a.shape

(2,)

In [315]:
b = np.array([3, 4, 6])
b.shape

(3,)

In [316]:
try:
    a + b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


In [317]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [318]:
b = a

In [319]:
b

array([[1, 2],
       [3, 4]])

In [320]:
b[0] = 999
a

array([[999, 999],
       [  3,   4]])

In [321]:
b

array([[999, 999],
       [  3,   4]])

In [322]:
f = np.array([4, 5, 6, 7, 8])
e = f.copy()

g = f[:]
g.base


array([4, 5, 6, 7, 8])

In [323]:
np.may_share_memory(g, f)

True

In [324]:
l = list(range(1, 10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [325]:
index = 1
l.__getitem__(index)

2

In [326]:
index = slice(1, 3)
l.__getitem__(index)

[2, 3]

In [327]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
index = 1
a.__getitem__(index)

2

In [328]:
index = slice(1, 3)
a.__getitem__(index)

array([2, 3])

In [329]:
index = 1
a.__getitem__(index)

2

In [330]:
index = [1]
a.__getitem__(index)

array([2])

In [331]:
index = a < 4
index

array([ True,  True,  True, False, False, False, False])

In [332]:
a.__getitem__(index)

array([1, 2, 3])

In [333]:
a = np.array(43)
type(a)


numpy.ndarray

In [334]:
a

array(43)

In [335]:
a.ndim

0

In [336]:
a.shape

()

In [337]:
a.dtype

dtype('int32')

In [338]:
a == 43

True

In [339]:
v = np.array([43])
type(v)

numpy.ndarray

In [340]:
v

array([43])

In [341]:
v.ndim

1

In [342]:
v.shape

(1,)

In [343]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [344]:
v.dtype

dtype('int32')

In [345]:
v1 = np.arange(10.5, 20.5, 0.5)
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [346]:
v1.dtype

dtype('float64')

In [347]:
v1.size

20

In [348]:
la = np.linspace(1, 10, 10)
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [349]:
la.dtype

dtype('float64')

In [350]:
la1 = np.linspace(1, 10, 10, endpoint = False, retstep = True)
la1

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [351]:
lo = np.logspace(0, 2, 4)
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [352]:
la2 = np.linspace(0, 2, 4)
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [353]:
for i in la2:
    print(np.power(10, i))

1.0
4.641588833612778
21.544346900318832
100.0


In [354]:
v = np.arange(3, 5)
v

array([3, 4])

In [355]:
np.hypot(v[0], v[1])

5.0

In [356]:
v_p = np.power(v, 2)

In [357]:
v_r = np.sqrt(np.sum(v_p))
v_r

5.0

In [358]:
np.linalg.norm(v)

5.0

In [359]:
e1 = np.array([1, 0, 0])
np.linalg.norm(e1)

1.0

In [360]:
e2 = np.array([0, 1, 0])
np.linalg.norm(e2)

1.0

In [361]:
e3 = np.array([0, 0, 1])
np.linalg.norm(e3)

1.0

In [362]:
v_3 = np.array([1, 2, 3])
v_3_n = np.linalg.norm(v_3)
v_3_n

3.7416573867739413

In [363]:
v_3_u = v_3 / v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [364]:
np.linalg.norm(v_3_u)

1.0

In [365]:
a = np.arange(3, 5)
b = np.arange(3, 5)
np.array_equal(a, b)

True

In [366]:
a_1 = np.linalg.norm(a)
b_1 = np.linalg.norm(b)
a_1 == b_1

True

In [367]:
c = np.arange(10, 13)
d = np.arange(0, 3)
np.sqrt(np.sum(np.square(c - d)))

17.320508075688775

In [368]:
np.linalg.norm(c - d)

17.320508075688775

In [369]:
A = np.array([[43], [44]])
type(A)

numpy.ndarray

In [370]:
A

array([[43],
       [44]])

In [371]:
A.dtype

dtype('int32')

In [372]:
A.ndim

2

In [373]:
A.shape

(2, 1)

In [374]:
c1 = np.array([[1, 2, 4], [2, 4, 8], [3, 4, 5]])
np.linalg.matrix_rank(c1)

2

In [375]:
c2 = np.array([[1, 3, 4], [1, 8, 5], [2, 3, 4]])
np.linalg.matrix_rank(c2)

3

In [376]:
np.linalg.det(c1)

0.0

In [377]:
c1[0] * 2 - c1[1]

array([0, 0, 0])

In [378]:
np.linalg.det(c2)

-17.0

In [379]:
np.linalg.matrix_rank(c2.T)

3

In [380]:
A = np.array([[2, 3], [4, 5]])
A.sum()

14

In [381]:
A.sum(axis = 0)

array([6, 8])

In [382]:
A.sum(axis = 1)

array([5, 9])

In [383]:
C = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
C.ndim

3

In [384]:
C.shape

(2, 2, 2)

In [385]:
C[0]

array([[1, 2],
       [3, 4]])

In [386]:
C[1]

array([[5, 6],
       [7, 8]])

In [387]:
C.sum(axis = 0)

array([[ 6,  8],
       [10, 12]])

In [388]:
C.sum(axis = 1)

array([[ 4,  6],
       [12, 14]])

In [389]:
C.sum(axis = 2)

array([[ 3,  7],
       [11, 15]])

In [390]:
x = np.array([1, 2])
x

array([1, 2])

In [391]:
x = np.array([[1, 4, 5], [4, 5, 6], [7, 8, 9]])
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [392]:
y = np.expand_dims(x, axis = 1)
y

array([[[1, 4, 5]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [393]:
z = np.expand_dims(x, axis = 0)
z

array([[[1, 4, 5],
        [4, 5, 6],
        [7, 8, 9]]])

In [394]:
x.flatten()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [395]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [396]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [397]:
a.shape

(3, 3)

In [398]:
np.trace(a)

14

In [399]:
a.trace()

14

In [400]:
b = np.array([[1, 0, 0], [0, 3, 0], [0, 0, 5]])
b

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [401]:
b.diagonal()

array([1, 3, 5])

In [402]:
np.diagonal(b)

array([1, 3, 5])

In [403]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [404]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [405]:
b = np.arange(1, 10).reshape(3, 3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [406]:
np.triu(b)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [407]:
X = np.array([[1, 2, 3], [2, 3, 5], [3, 5, 6]])
X

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [408]:
np.array_equal(X, X.T)

True

In [409]:
np.array_equiv(X, X.T)

True

In [410]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [411]:
b = np.eye(3, dtype = 'int')
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [412]:
np.dot(a, b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [413]:
c = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
np.dot(a, c)

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [414]:
from scipy.stats import ortho_group

In [415]:
x = ortho_group.rvs(3)

In [416]:
x

array([[-0.09591173, -0.34567385, -0.93344016],
       [-0.5058138 ,  0.82458811, -0.25339072],
       [ 0.8572942 ,  0.44784377, -0.25393427]])

In [417]:
i3 = np.dot(x, x.T)
i3

array([[ 1.00000000e+00,  1.38127894e-16, -2.56723876e-16],
       [ 1.38127894e-16,  1.00000000e+00, -2.90942796e-17],
       [-2.56723876e-16, -2.90942796e-17,  1.00000000e+00]])

In [418]:
c = np.eye(3)
np.allclose(c, i3)

True

In [419]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [420]:
a.T

array([[1, 3],
       [2, 4]])

In [421]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [422]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [423]:
v = np.array([1,2,3,4,5])
v[0]

1

In [424]:
v[-1]

5

In [425]:
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
A[0]

array([1, 2, 3, 4, 5])

In [426]:
A[-1]

array([ 6,  7,  8,  9, 10])

In [427]:
B = np.arange(9).reshape(3, 3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [428]:
B.shape

(3, 3)

In [429]:
B[0, :]

array([0, 1, 2])

In [430]:
B[0]

array([0, 1, 2])

In [431]:
B[:, 0]

array([0, 3, 6])

In [432]:
A = np.arange(1, 60, 5).reshape(3, 4)
A

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [433]:
# 113page
A[...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [434]:
A[:2, ...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36]])

In [435]:
A[..., :2]

array([[ 1,  6],
       [21, 26],
       [41, 46]])

In [436]:
L = np.random.randn(7, 4)
L

array([[-0.28216642,  0.4325581 ,  0.20129144, -0.01636966],
       [-1.23976553,  0.34377207, -0.36211841, -1.15612201],
       [-0.35259618,  0.37321733, -1.03030331, -1.19578351],
       [ 0.92350747,  0.44212986,  0.79830347,  0.83648947],
       [ 0.43678043,  1.13917134, -0.22572127, -0.59276943],
       [ 0.39081839,  0.92087609,  0.20163323,  1.33909109],
       [ 1.87645886, -2.07520861,  0.45275202, -0.82247294]])

In [437]:
L[L < 0]

array([-0.28216642, -0.01636966, -1.23976553, -0.36211841, -1.15612201,
       -0.35259618, -1.03030331, -1.19578351, -0.22572127, -0.59276943,
       -2.07520861, -0.82247294])

In [438]:
L[L < 0] = 999
L

array([[9.99000000e+02, 4.32558097e-01, 2.01291442e-01, 9.99000000e+02],
       [9.99000000e+02, 3.43772069e-01, 9.99000000e+02, 9.99000000e+02],
       [9.99000000e+02, 3.73217329e-01, 9.99000000e+02, 9.99000000e+02],
       [9.23507473e-01, 4.42129861e-01, 7.98303472e-01, 8.36489473e-01],
       [4.36780430e-01, 1.13917134e+00, 9.99000000e+02, 9.99000000e+02],
       [3.90818387e-01, 9.20876091e-01, 2.01633235e-01, 1.33909109e+00],
       [1.87645886e+00, 9.99000000e+02, 4.52752015e-01, 9.99000000e+02]])

In [439]:
LC = L[L == 999]
LC

array([999., 999., 999., 999., 999., 999., 999., 999., 999., 999., 999.,
       999.])

In [440]:
L = np.arange(0, 12)
L

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [441]:
try:
    L and L

except Exception as e:
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [442]:
np.logical_and(L, L)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [443]:
L[np.logical_and(L, L)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [444]:
x = np.arange(1, 15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [445]:
pos2 = np.array([1, 2, 2, 2])
x[pos2]

array([2, 3, 3, 3])

In [446]:
c = x[pos2]
np.may_share_memory(x, c)

False

In [447]:
y = x[:4]
np.may_share_memory(x, y)

True

In [448]:
x = np.arange(16).reshape(4, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [449]:
x[[3, 0]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [450]:
x[[1, 2], [2, 3]]

array([ 6, 11])

In [451]:
a = np.array([[2, 3, 4, 5], [8, 9, 0, 1]])
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [452]:
type(np.ix_)

function

In [453]:
a[np.ix_([0, 1], [0, 1])]

array([[2, 3],
       [8, 9]])

In [454]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [455]:
x[0, [0, 1]]

array([0, 1])

In [456]:
x[1, [0, 1]]

array([5, 6])

In [457]:
x[[0, 1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [458]:
x[[0, 1], 0]

array([0, 5])

In [459]:
a = x[[0, 1], 0]
a

array([0, 5])

In [460]:
np.may_share_memory(x, a)

False

In [461]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [462]:
a = x[1:, 1:]
a

array([[4, 5],
       [7, 8]])

In [463]:
np.may_share_memory(x, a)

True

In [464]:
a = np.reshape(np.arange(10), (2, 5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [465]:
c = a[[1, 1, 1], np.newaxis]
c.shape

(3, 1, 5)

In [466]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [467]:
x.item(1)

1

In [468]:
x.item(5)

5

In [469]:
x.item(1, 2)

5

In [470]:
x.item((2, 2))

8

In [471]:
x.itemset(2, 20)
x

array([[ 0,  1, 20],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [472]:
x.itemset((1, 2), 20)
x

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [473]:
x.view()

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [474]:
b = np.linspace(1, 10, 10).reshape(2, 5)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [475]:
pos1 = [3, 4]
b.take(pos1)

array([4., 5.])

In [476]:
pos2 = [[0, 1], [3, 4]]
b.take(pos2)

array([[1., 2.],
       [4., 5.]])

In [477]:
c = b.copy()
np.may_share_memory(c, b)

False

In [478]:
c.put(pos1, 30)
c

array([[ 1.,  2.,  3., 30., 30.],
       [ 6.,  7.,  8.,  9., 10.]])

In [479]:
c.put(pos1, [50, 50])
c

array([[ 1.,  2.,  3., 50., 50.],
       [ 6.,  7.,  8.,  9., 10.]])

In [480]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [481]:
np.choose(0, x)


array([0, 1, 2])

In [482]:
np.choose([0], x)

array([0, 1, 2])

In [483]:
np.choose(tuple([0, 1, 2]), x)

array([0, 4, 8])

In [484]:
np.choose(tuple([2, 1, 0]), x)

array([6, 4, 2])

In [485]:
np.where(x > 4)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [486]:
x[np.where(x > 4)]

array([5, 6, 7, 8])

In [487]:
a = np.select(x > 5, x * 2)
a

array([12, 14, 16])

In [488]:
np.extract(x > 4, x)

array([5, 6, 7, 8])

In [489]:
d = np.array([3, 4])
e = np.array([5, 6])
d + e

array([ 8, 10])

In [490]:
np.add(d, e)

array([ 8, 10])

In [491]:
f = np.array([1, 2, 3])

try:
    f + e
except Exception as ex:
    print(ex)

operands could not be broadcast together with shapes (3,) (2,) 


In [492]:
d = np.array([3, 4])
e = np.array([5, 6])

d - e

array([-2, -2])

In [493]:
np.subtract(d, e)

array([-2, -2])

In [494]:
d + (-e)

array([-2, -2])

In [495]:
np.add(d, np.negative(e))

array([-2, -2])

In [496]:
d = np.array([2, 3])
3 * d

array([6, 9])

In [497]:
np.array([3, 3]) * d

array([6, 9])

In [498]:
np.multiply(3, d)

array([6, 9])

In [499]:
np.multiply(np.array([3, 3]), d)

array([6, 9])

In [500]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [501]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [502]:
z = np.broadcast(x, y)
z

In [503]:
type(z)

numpy.broadcast

In [504]:
z.shape, z.ndim

((2, 5), 2)

In [505]:
for i in z:
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 0)
(6, 1)
(7, 2)
(8, 3)
(9, 4)


In [506]:
x + y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [507]:
x2 = np.ones((2, 3))
x2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [508]:
x1 = np.ones(3)
x1

array([1., 1., 1.])

In [509]:
x1.shape, x2.shape

((3,), (2, 3))

In [510]:
x1.shape[0] == x2.shape[1]

True

In [511]:
x1 = x1[np.newaxis,]
x1.shape

(1, 3)

In [512]:
x1 = np.vstack((x1[0], x1[0]))
x1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [513]:
x1.shape == x2.shape

True

In [514]:
x1 + x2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [515]:
x = np.arange(1, 4)
x

array([1, 2, 3])

In [516]:
x1 = x.reshape(1, 3)
x1

array([[1, 2, 3]])

In [517]:
x2 = x[np.newaxis,]
x2

array([[1, 2, 3]])

In [518]:
y = np.arange(1, 4)
y

array([1, 2, 3])

In [519]:
y1 = y.reshape(3, 1)
y1

array([[1],
       [2],
       [3]])

In [520]:
y2 = y[:, np.newaxis]
y2

array([[1],
       [2],
       [3]])

In [521]:
np.broadcast_arrays(x1, y1)

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])]

In [522]:
x1 + y1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [523]:
a = np.array([3, 4])
b = np.array([5, 6])
a @ b

39

In [524]:
np.dot(a, b)

39

In [525]:
np.inner(a, b)

39

In [526]:
a = np.array([1, 4])
b = np.array([3, 6])
np.cross(a, b)

array(-6)

In [527]:
c = np.array([1, 4, 3])
d = np.array([3, 4, 5])
np.cross(c, d)

array([ 8,  4, -8])

In [528]:
a = np.array([[3, 4], [5, 6]])
a

array([[3, 4],
       [5, 6]])

In [529]:
b = np.array([[5, 6], [6, 7]])
b

array([[5, 6],
       [6, 7]])

In [530]:
np.dot(a, b)


array([[39, 46],
       [61, 72]])

In [531]:
a.dot(b)

array([[39, 46],
       [61, 72]])

In [532]:
a @ b

array([[39, 46],
       [61, 72]])

In [533]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.dot(a, b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [537]:
c = b[:, 0]
d = b[:, 1]
e = b[:, 2]

c = c[:, np.newaxis]
d = d[:, np.newaxis]
e = e[:, np.newaxis]

f = a @ c
g = a @ d
h = a @ e

i = np.concatenate([f, g, h], axis = 1)
i


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [538]:
a = np.array([[3, 1], [2, 2]])
np.linalg.det(a)

4.000000000000001

In [539]:
np.allclose(4.0, np.linalg.det(a))

True

In [540]:
b = np.array([[3, 1, 3], [2, 2, 3], [1, 1, 1]])
b

array([[3, 1, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [541]:
3 * np.linalg.det(b[1:, 1:])

-3.0

In [542]:
np.linalg.det(b[1:, ::2])

-1.0

In [543]:
3 * np.linalg.det(b[1:, :2])

0.0

In [544]:
np.linalg.det(b)

-2.0000000000000004

In [545]:
-3 + 1 + 0

-2

In [546]:
a = np.array([[3, 2], [6, 4]])
np.linalg.det(a)

0.0

In [547]:
b = np.array([[1, 2, 3], [4, 5, 6], [3, 2, 4]])
np.linalg.det(b)

-9.000000000000002

In [548]:
bi = np.linalg.inv(b)
bb = np.dot(b, bi)
np.allclose(np.eye(3), bb)


True

In [549]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [550]:
ai = np.linalg.inv(a)
ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [551]:
x = np.dot(a, ai)
x

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [552]:
np.allclose(np.eye(2), x)

True

In [553]:
y = np.dot(ai, a)
y

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [554]:
np.allclose(np.eye(2), y)

True

In [555]:
np.allclose(x, y)

True

In [556]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

In [557]:
b = np.array([[3, 4], [1, 2]])
np.linalg.det(b)

2.0000000000000004

In [558]:
ai = np.linalg.inv(a)
bi = np.linalg.inv(b)

ab = np.linalg.inv(np.dot(a, b))
ba = np.dot(bi, ai)
np.allclose(ab, ba)

True

In [559]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [560]:
x1 = x.reshape(2, 8)
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [561]:
try:
    x2 = x.reshape(4, 5)

except Exception as e:
    print(e)

cannot reshape array of size 16 into shape (4,5)


In [562]:
y1 = x.reshape(4, -1)
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [563]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [564]:
np.resize(a, 8)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [565]:
np.append(a, a)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [566]:
b = np.arange(4)
b.resize((4, 4))
b

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [567]:
c = np.arange(8)
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [568]:
c.resize(4, refcheck = False)
c

array([0, 1, 2, 3])

In [569]:
x = np.arange(3)
y = np.arange(4)

x_, y_ = np.meshgrid(x, y)
x_

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [570]:
y_

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [571]:
x_1 = x.reshape(1, -1)
np.concatenate([x_1, x_1, x_1, x_1])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [572]:
y_1 = y.reshape(-1, 1)
np.concatenate([y_1, y_1, y_1, y_1], axis = 1)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [573]:
np.arange(10, 30, 10)

array([10, 20])

In [574]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [575]:
np.broadcast_arrays(np.arange(10, 30, 10).reshape(2, 1), np.arange(1, 5).reshape(1, 4))

[array([[10, 10, 10, 10],
        [20, 20, 20, 20]]),
 array([[1, 2, 3, 4],
        [1, 2, 3, 4]])]

In [576]:
a, b = np.mgrid[10:30:10, 1:5]
a

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [577]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [578]:
c, d = np.ogrid[10:30:10, 1:5]
c

array([[10],
       [20]])

In [579]:
d

array([[1, 2, 3, 4]])

In [580]:
e, f = np.broadcast_arrays(c, d)

In [581]:
e

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [582]:
f

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [583]:
x = np.array([[[0], [1], [2]]])
x

array([[[0],
        [1],
        [2]]])

In [584]:
x.shape

(1, 3, 1)

In [585]:
np.squeeze(x)

array([0, 1, 2])

In [586]:
np.squeeze(x, axis = 0)

array([[0],
       [1],
       [2]])

In [587]:
np.squeeze(x, axis = 2)

array([[0, 1, 2]])

In [588]:
a = np.linspace(1, 5, 5, dtype = np.int32)
a

array([1, 2, 3, 4, 5])

In [589]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [590]:
e = np.arange(4).reshape(2, 2)
e

array([[0, 1],
       [2, 3]])

In [591]:
np.tile(e, 2)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [593]:
a = np.linspace(1, 6, 6, dtype = np.int32).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [595]:
b = np.linspace(7, 13, 6, dtype = np.int32).reshape(2, 3)
b

array([[ 7,  8,  9],
       [10, 11, 13]])

In [596]:
np.concatenate([a, b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]])

In [597]:
np.concatenate([a, b], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 13]])

In [598]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.stack([x, y])

array([[1, 2, 3],
       [4, 5, 6]])

In [599]:
np.stack([x, y], axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [600]:
a = np.vstack([x, y])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [601]:
np.vstack([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [602]:
np.stack([x, y], axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [603]:
b = np.hstack([x, y])
b

array([1, 2, 3, 4, 5, 6])

In [604]:
a = np.linspace(1, 6, 6, dtype = np.int32).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [605]:
b = np.vstack([a, a])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [606]:
x, y = np.split(b, [2])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [607]:
y

array([[1, 2, 3],
       [4, 5, 6]])