In [19]:
from AutoEncoderModule import *
import torch
import torch.nn as nn
import numpy as np
import pickle

In [ ]:
ELEC_SCALER_PATH = './electric_min_max_scaler.pkl'
WATER_SCALER_PATH = './water_robust_scaler.pkl'

ELEC_MODEL_PATH = './model_weights_89.pth'
WATER_MODEL_PATH = './model_weights_166.pth'

In [77]:
# water_list = [93,49,-93,-72,-36,194,-107,-50,60,111,-81,-27,37,23,-72,-51,65,77,-73,-47,93,49,-93,-20,10,0,0]
elec_list = [1.73,1.62,1.31,1.48,1.74,1.71,1.3,1.49,1.94,1.68,1.26,1.39,1.69,1.61,1.28,1.44,1.77,1.68,1.2,1.42,1.88,1.67,1.24,1.39,1.2,1.2, 1.2, 1.2]

In [78]:
with open(ELEC_SCALER_PATH, 'rb') as f:
    elec_scaler = pickle.load(f)

with open(WATER_SCALER_PATH, 'rb') as f:
    water_scaler = pickle.load(f)

elec_df = pd.DataFrame(columns = range(28))
elec_df.loc[0] = elec_list

# water_df = pd.DataFrame(columns = range(27))
# water_df.loc[0] = water_list

scaled_elec = elec_scaler.transform(elec_df)
# scaled_water = water_scaler.transform(water_df)

elec_ts = torch.FloatTensor(scaled_elec)
# water_ts = torch.FloatTensor(scaled_water)

elec_ts



c:\Users\KDP-2\anaconda3\envs\Project_38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


tensor([[0.6250, 0.5000, 0.1477, 0.3409, 0.6364, 0.6023, 0.1364, 0.3523, 0.8636,
         0.5682, 0.0909, 0.2386, 0.5795, 0.4886, 0.1136, 0.2955, 0.6705, 0.5682,
         0.0227, 0.2727, 0.7955, 0.5568, 0.0682, 0.2386, 0.0227, 0.0227, 0.0227,
         0.0227]])

In [79]:
water_ts

NameError: name 'water_ts' is not defined

In [80]:
input_size = 27
hidden_dim = 128

water_model = VanillaModel(input_size = input_size, hidden_dim = hidden_dim)
water_model.load_state_dict(torch.load(WATER_MODEL_PATH, map_location = torch.device('cpu'), weights_only = True))
water_model.eval()

water_predict_value = water_model(water_ts)
water_predict_value

NameError: name 'water_ts' is not defined

In [81]:
input_size = 28
hidden_dim = 256

elec_model = VanillaModel(input_size = input_size, hidden_dim = hidden_dim)
elec_model.load_state_dict(torch.load(ELEC_MODEL_PATH, map_location = torch.device('cpu'), weights_only = True))
elec_model.eval()

elec_predict_value = elec_model(elec_ts)
elec_predict_value

tensor([[0.6251, 0.4984, 0.1180, 0.3283, 0.6524, 0.6007, 0.1739, 0.3552, 0.8601,
         0.5720, 0.0842, 0.2269, 0.5967, 0.4770, 0.0878, 0.2365, 0.6819, 0.5540,
         0.0780, 0.3602, 0.7878, 0.6314, 0.0513, 0.1012, 0.1039, 0.1070, 0.0874,
         0.0208]], grad_fn=<AddmmBackward0>)

In [82]:
elec_scaler.inverse_transform(elec_predict_value.detach().numpy())

array([[1.7300507, 1.6185739, 1.2838594, 1.4689155, 1.7540829, 1.7086508,
        1.3330611, 1.4925996, 1.936863 , 1.6833357, 1.2541289, 1.3796595,
        1.7051294, 1.5997428, 1.2572595, 1.3881507, 1.7800292, 1.6675302,
        1.2486577, 1.4969479, 1.8732288, 1.7356366, 1.2251221, 1.2690616,
        1.271407 , 1.2741516, 1.2569125, 1.1983331]], dtype=float32)

In [83]:
elec_list

[1.73,
 1.62,
 1.31,
 1.48,
 1.74,
 1.71,
 1.3,
 1.49,
 1.94,
 1.68,
 1.26,
 1.39,
 1.69,
 1.61,
 1.28,
 1.44,
 1.77,
 1.68,
 1.2,
 1.42,
 1.88,
 1.67,
 1.24,
 1.39,
 1.2,
 1.2,
 1.2,
 1.2]

In [9]:
nn.L1Loss()(elec_ts, elec_predict_value)

tensor(0.0101, grad_fn=<MeanBackward0>)

In [ ]:
input_size = 28
hidden_dim = 64

water_model = VanillaModel(input_size = input_size, hidden_dim = hidden_dim)
water_model.load_state_dict(torch.load(WATER_MODEL_PATH, map_location = torch.device('cpu'), weights_only = True))
water_model.eval()

water_predict_value = water_model(water_ts)
water_predict_value

tensor([[-1.3244, -1.3244, -1.3244,  0.8375, -1.2344,  3.1784,  0.5044,  0.6213,
         -0.9368, -0.1010,  0.3785, -0.5680, -0.8375, -0.0541,  0.3681, -0.4689,
         -0.9097, -0.0727,  0.5099,  0.4595, -0.8462,  0.1329,  0.5670,  0.0267,
          3.2718,  2.5486,  3.1794,  3.1798]], grad_fn=<AddmmBackward0>)

In [ ]:
water_ts

tensor([[-1.3243, -1.3243, -1.3243,  0.8378, -1.2342,  3.1802,  0.5045,  0.6216,
         -0.9369, -0.0991,  0.3784, -0.5676, -0.8378, -0.0541,  0.3694, -0.4685,
         -0.9099, -0.0721,  0.5135,  0.4595, -0.8468,  0.1351,  0.5676,  0.0270,
          3.2703,  2.5495,  3.1802,  3.1802]])

In [ ]:
nn.L1Loss()(water_ts, water_predict_value)

tensor(0.0007, grad_fn=<MeanBackward0>)