In [14]:
import numpy as np

In [15]:
a = np.arange(6).reshape(2, 3)
c = np.random.randn(2, 3)
np.r_[a, c]

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [-1.64656654,  0.07224624, -0.4714393 ],
       [ 0.57843893, -0.67071086, -0.70433463]])

In [16]:
np.c_[a, c]

array([[ 0.        ,  1.        ,  2.        , -1.64656654,  0.07224624,
        -0.4714393 ],
       [ 3.        ,  4.        ,  5.        ,  0.57843893, -0.67071086,
        -0.70433463]])

In [17]:
a = np.linspace(1, 6, 6, dtype = np.int32)
a

array([1, 2, 3, 4, 5, 6])

In [18]:
np.random.shuffle(a)
a

array([4, 2, 3, 5, 1, 6])

In [19]:
b = np.sort(a)
b

array([1, 2, 3, 4, 5, 6])

In [20]:
a

array([4, 2, 3, 5, 1, 6])

In [21]:
a.sort()

In [22]:
a

array([1, 2, 3, 4, 5, 6])

In [24]:
bb = np.linspace(1, 6, 6, dtype = np.int32)
bb

array([1, 2, 3, 4, 5, 6])

In [25]:
np.random.shuffle(bb)
bb

array([1, 6, 4, 5, 2, 3])

In [26]:
c = np.argsort(bb)
c

array([0, 4, 5, 2, 3, 1], dtype=int64)

In [27]:
bb[c[0]]

1

In [28]:
bb[c[1]]

2

In [29]:
m = np.matrix([1, 2, 3, 4])
m

matrix([[1, 2, 3, 4]])

In [30]:
type(m)

numpy.matrix

In [31]:
a = np.asarray(m)
a

array([[1, 2, 3, 4]])

In [32]:
type(a)

numpy.ndarray

In [33]:
m1 = np.asmatrix(a)
m1

matrix([[1, 2, 3, 4]])

In [34]:
o = np.ones(10)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
# 있는거에다가 집어넣음

o.fill(100)
o

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [36]:
# shape 모양대로 새로운 변수에 숫자를 채움
a = np.full(o.shape, 99.)
a

array([99., 99., 99., 99., 99., 99., 99., 99., 99., 99.])

In [37]:
array = np.arange(4).reshape((2, 2))
array

array([[0, 1],
       [2, 3]])

In [38]:
np.fliplr(array)

array([[1, 0],
       [3, 2]])

In [39]:
np.flipud(array)

array([[2, 3],
       [0, 1]])

In [40]:
m = np.array([[1,2], [3, 4]], int)
m

array([[1, 2],
       [3, 4]])

In [41]:
np.rot90(m)

array([[2, 4],
       [1, 3]])

In [42]:
np.rot90(m, 2)

array([[4, 3],
       [2, 1]])

In [43]:
np.rot90(m, 3)

array([[3, 1],
       [4, 2]])

In [44]:
np.rot90(m, 4)

array([[1, 2],
       [3, 4]])

In [45]:
m = np.random.randn(3, 5)
m

array([[ 0.92093957, -0.83219256, -1.33168507, -0.88496441, -1.75864875],
       [ 1.62192971, -0.91984831, -1.59104374,  1.27975431, -1.03447845],
       [-1.25307757,  0.2376178 , -0.49677902, -1.14487049,  1.24713445]])

In [46]:
np.isreal(m)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [47]:
np.isinf(m)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [48]:
np.isnan(m)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [49]:
x = np.arange(1, 5).reshape(2, 2)
x

array([[1, 2],
       [3, 4]])

In [50]:
z = np.zeros((3, 3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
z[:2, :2] = x

In [52]:
z

array([[1., 2., 0.],
       [3., 4., 0.],
       [0., 0., 0.]])

In [53]:
np.pad(x, 0, "constant")

array([[1, 2],
       [3, 4]])

In [54]:
np.pad(x, (0, 1), "constant")

array([[1, 2, 0],
       [3, 4, 0],
       [0, 0, 0]])

In [55]:
np.pad(x, (1, 0), "constant")

array([[0, 0, 0],
       [0, 1, 2],
       [0, 3, 4]])

In [56]:
np.pad(x, (1, 1), "constant")

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [57]:
np.pad(x, (3, 3), "constant")

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [59]:
x = np.arange(1, 5).reshape(2, 2)
x

array([[1, 2],
       [3, 4]])

In [60]:
np.pad(x, (0, 1), "edge")

array([[1, 2, 2],
       [3, 4, 4],
       [3, 4, 4]])

In [61]:
np.pad(x, (1, 0), "edge")

array([[1, 1, 2],
       [1, 1, 2],
       [3, 3, 4]])

In [62]:
np.pad(x, (1, 1), "edge")

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [63]:
np.pad(x, (3, 3), "edge")

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4]])

In [64]:
np.pad(x, (3, 3), "maximum")

array([[4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4]])

In [65]:
np.pad(x, (3, 3), "minimum")

array([[1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [3, 3, 3, 3, 4, 3, 3, 3],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1]])

In [66]:
np.pad(x, (1, 1), "mean")

array([[2, 2, 3, 2],
       [2, 1, 2, 2],
       [4, 3, 4, 4],
       [2, 2, 3, 2]])

In [67]:
np.pad(x, (3, 3), "mean")

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])

In [68]:
np.pad(x, (3, 3), "median")

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])

In [69]:
np.dtype

numpy.dtype

In [70]:
d = np.dtype(np.int32)
d

dtype('int32')

In [71]:
a = np.array([1, 2, 3, 4], dtype = d)
a

array([1, 2, 3, 4])

In [72]:
a.dtype

dtype('int32')

In [73]:
np.int_

numpy.int32

In [74]:
np.int_.mro()

[numpy.int32,
 numpy.signedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [75]:
issubclass(np.int32, np.signedinteger)

True

In [77]:
issubclass(np.integer, np.number)

True

In [78]:
issubclass(np.number, np.generic)

True

In [79]:
p_i = int(100)
p_i

100

In [80]:
n_i = np.int32(100)
n_i

100

In [81]:
p_i + n_i

200

In [82]:
np.datetime64

numpy.datetime64

In [83]:
print(np.datetime64)

<class 'numpy.datetime64'>


In [84]:
y = np.datetime64('2018')

In [85]:
y, y.dtype

(numpy.datetime64('2018'), dtype('<M8[Y]'))

In [86]:
ym = np.datetime64('2018-11')
ym, ym.dtype

(numpy.datetime64('2018-11'), dtype('<M8[M]'))

In [87]:
ymd = np.datetime64('2018-11-15')
ymd, ymd.dtype

(numpy.datetime64('2018-11-15'), dtype('<M8[D]'))

In [88]:
a = np.array(['2018-11-15', '2018-12-15', '2018-01-15'],
             dtype = np.datetime64)
a

array(['2018-11-15', '2018-12-15', '2018-01-15'], dtype='datetime64[D]')

In [89]:
delta = np.datetime64('2018-11-15') - np.datetime64('2016-11-15')
delta, delta.dtype

(numpy.timedelta64(730,'D'), dtype('<m8[D]'))

In [90]:
print(delta)

730 days


In [91]:
np.str_, np.unicode_

(numpy.str_, numpy.str_)

np.str_ is str, np.unicode_ is str

In [100]:
np.str_ is bytes, np.unicode_ is bytes

(False, False)