#### Tensor 변환
- torch.as_tensor()
    * 동일 타입과 디바이스를 가진 데이터 존재 ==> view 즉, 데이터 공유
    * 다른 타입 또는 다른 디바이스를 가진 데이터 존재 ==> copy 즉, 생성
    * view tensor 또는 copy tensor 반환

In [1]:
import torch


- Python 객체 ==> Tensor 변환

In [2]:
## List ==> Tensor
data = list(range(1, 10))

In [5]:
## torch.as_tensor()
dataTS = torch.as_tensor(data, dtype = torch.uint8)
dataTS, dataTS.shape, dataTS.ndim

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.uint8), torch.Size([9]), 1)

In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr1, arr1.dtype, arr1.ndim

(array([1, 2, 3]), dtype('int32'), 1)

In [8]:
arrTS = torch.as_tensor(arr1, dtype = torch.float32)
arrTS

tensor([1., 2., 3.])

In [11]:
arr1[0] = 77

In [9]:
arrTS[0] = 99

In [12]:
arr1, arrTS

(array([77,  2,  3]), tensor([99.,  2.,  3.]))

- Numpy ndarray ==> Tensor 변환 : from_numpy()

In [19]:
arr1 = np.array([[5, 7, 9], [1, 2, 3]], dtype = np.float16)
print(arr1) 
print(F"데이터 저장 메모리 :    {arr1.data}")
print(f"원소/요소 개수 :        {arr1.size}")
print(F"원소/요소 1개 크기 :    {arr1.itemsize}")
print(F"타입              :    {arr1.dtype}")
print(F"방향              :    {arr1.strides}")

[[5. 7. 9.]
 [1. 2. 3.]]
데이터 저장 메모리 :    <memory at 0x000001D836F63D40>
원소/요소 개수 :        6
원소/요소 1개 크기 :    2
타입              :    float16
방향              :    (6, 2)


In [20]:
arrTS = torch.from_numpy(arr1)
arrTS

tensor([[5., 7., 9.],
        [1., 2., 3.]], dtype=torch.float16)